### ISSUE TITLE
pin code support

### ISSUE THREAD

**Issue by justeph** [tim-smart/vouchervault#12]
As discussed in https://github.com/tim-smart/vouchervault/pull/11 I  think it would be nice to have a pin code field: all the vouchers I personally use have a numeric pin code, making this a property of the vouchers itself. 
For now we can use the generic note field for that, but, IMHO it is more user friendly to have a dedicated pin code field: numeric keypad, lock icon... I would keep note fields for extra notes, not a frequent property of vouchers (for example it doesn't make sens to have the  `expires` and `balance`  inside the note field). 

Is there a motivation to not have this kind a pin code field?

**Comment by tim-smart** [comment]
The expires and balance fields are a bit different as they have functionality attached to them.

Pin code is purely informational, so can be covered off with the notes field.

I agree that a dedicated field would definitely be easier to use, but I want to avoid adding fields where possible to keep the app simple.

**Comment by justeph** [comment]
Hi @tim-smart ,

>Pin code is purely informational, so can be covered off with the notes field.

 I do not agree with you. Pin code is not purely informational, because when present it is mandatory for online shopping, and sometimes mandatory for offline shopping (talking about my personal experience here) 
 
>The expires and balance fields are a bit different as they have functionality attached to them.

We can imagine that taping on pinCode can copy it into the clipboard (such as typing on barcode), that would be useful for online shopping on mobile ;) 

At the end of the day, it is you app, so it is your decision  :)

**Comment by tim-smart** [comment]
Copy to clipboard is understandable. I'll make the notes field selectable as a middle ground :)

My decision is to not add this field right now. Sorry!
