### ISSUE TITLE
EAN 128 support

### ISSUE THREAD

**Issue by mdvhimself** [tim-smart/vouchervault#13]
Would it be possible to add GS1-128 (UCC/EAN-128) ? Tesco is using this format for its club card. So far i was able to add any card and voucher and even tickets...but i wouldnt mind leavng one more card at home. Thank you in advance!

**Comment by tim-smart** [comment]
GS1-128 is just a code128 barcode with a specific data format, from what I understand?

**Comment by TIZEMNODA** [comment]
😜

**Comment by mdvhimself** [comment]
![image](https://user-images.githubusercontent.com/13852027/152964491-71274edf-519f-4d0c-a9e2-ffa69e6f2d16.png)
its a simple barcode, but other format yes

**Comment by shompoe** [comment]
Hi,  I just found that the Clubcard number is not the same as the barcode on the card. You can try this app to see for yourself, and find out what code you need to enter into Voucher Vault.

https://play.google.com/store/apps/details?id=com.idautomation.decoder

**Comment by mdvhimself** [comment]
the picture above is from a legit stocard screenshot . stocard was able to scan it, and identified it as ean128. feel free to install and try. neither catima, vouchervault, and not even googlepay supports the format, so not much point linking me an even worse database.
