### ISSUE TITLE
Wanna work together?

### ISSUE THREAD

**Issue by TheLastProject** [tim-smart/vouchervault#4]
Hey,

I am the maintainer of [Catima](https://github.com/TheLastProject/Catima) and I've been noticing your app on F-Droid. It's pretty neat.

I was wondering, would you care to keep our apps interoperable? So users can switch between them (within reason, of course, we have some differences in what values we do or do not accept).

I've documented how an export for Catima looks on https://github.com/TheLastProject/Catima/wiki/Export-format and how the card sharing URL is formatted on https://github.com/TheLastProject/Catima/wiki/Card-sharing-URL-format.

Would you be willing to document your export format? And is there any way we could keep each other up to date if it ever changes?

Thanks!

- Sylvia

**Comment by tim-smart** [comment]
I'm using JSON for the export format, for example:

```json
[
  {
    "uuid": "faecb247-b99d-466b-83e3-cb1f38af1f3c",
    "description": "Smartfuel",
    "code": "12345",
    "codeType": "CODE128",
    "expires": null,
    "removeOnceExpired": true,
    "balance": null,
    "color": "ORANGE"
  },
  {
    "uuid": "3a7362d9-ef19-4338-9e38-bad00beaf9d6",
    "description": "Subway",
    "code": "12345",
    "codeType": "QR",
    "expires": null,
    "removeOnceExpired": true,
    "balance": null,
    "color": "YELLOW"
  }
]
```

I built the app mainly for my own personal use, but if needed I can add some extra fields to the JSON output if that works.

There is no categories / labels in Voucher Vault, and the balance option only supports dollar amounts.

**Comment by TheLastProject** [comment]
I totally understand making it for personal use, that's the best way to write apps honestly :)

Catima doesn't support auto-removal when expiring so I will ignore that, but otherwise I'll try to create support for importing a Voucher Vault export into Catima. If possible, please tell me if you ever change anything in the export format so I can make sure to keep it compatible.

Please tell me if you ever give Voucher Vault support for important Catima backups so I can keep you updated if new fields or things get introduced. I'm also available to help if you want help :)

I'll close this now to keep your issue tracker clean because I have like all info I need from you, but feel free to reopen if you want my help for something :)

**Comment by TheLastProject** [comment]
In case you're curious I have implemented it in Catima here: https://github.com/TheLastProject/Catima/pull/159

Will probably be part of the next release.

I will only support importing from Voucher Vault, not exporting to Voucher Vault's format. That is not to lock in users, but just to keep the amount of work I need to do down (it makes more sense to me for each app to just export in its own format but support importing from multiple formats).

**Comment by tim-smart** [comment]
Cool thanks!
