### ISSUE TITLE
Cryptographic APIs misuses

### ISSUE THREAD

**Issue by misterAnderson90** [tim-smart/vouchervault#9]
I'm a PhD student interested in finding security vulnerabilities in open source projects.

We found a total of 3  warnings (indicating potential vulnerabilities) when running the CogniCrypt static analyzer (*) on vouchervault (or its library dependencies). We documented each one of these issues in private gists for the sake of confidentiality (non-disclosure). 

Can you please let us know whether we can share these gists with you? We are eager to evaluate the perception of developers (e.g. severity of these warnings) and improve vouchervault's security, and the quality of the reports of static analysis tools.
(*) https://github.com/CROSSINGTUD/CryptoAnalysis

**Comment by tim-smart** [comment]
Yes, feel free to share the results.

**Comment by misterAnderson90** [comment]
Hello Tim,

Thanks for your interest in receiving the gists. I have sent you by e-mail.

Please let me know if you have any questions.

**Comment by luisamaralh** [comment]
Hello @tim-smart, 

Did you have time to evaluate these issues? How do you perceive the warnings reported by this SAST tool?

**Comment by misterAnderson90** [comment]
Hello @tim-smart,

Did you have time to evaluate these issues? How do you perceive the warnings reported by this SAST tool?
